import type { ManagerDomainFactory } from '../manager/domain';
function buildStatusSection(statusPrompt: string): string {
    return [
        '---',
        '',
        '## Status Panel',
        '',
        'The status panel is a structured UI that you draw for the user. It is displayed persistently on the side of the screen.',
        'Every field you write is rendered into a visible interface element — you are composing a layout, not filling a data table.',
        '',
        'Visual structure: panel → selected subject → tabs → blocks → fields. The diagram below is inside one subject; meta.activeSubject selects the initial subject.',
        '',
        '```',
        '┌─ panel ──────────────────────────────┐',
        '│ ┌─ tab ──────────────────────────┐   │',
        '│ │ tab label → switchable tab     │   │',
        '│ │ ┌─ block ───────────────────┐  │   │',
        '│ │ │ block title → section     │  │   │',
        '│ │ │ block has exactly one     │  │   │',
        '│ │ │ form type                 │  │   │',
        '│ │ │ ┌─ field ──────────────┐  │  │   │',
        '│ │ │ │ each field renders   │  │  │   │',
        '│ │ │ │ as a row, tag, card  │  │  │   │',
        '│ │ │ └─────────────────────┘  │  │   │',
        '│ │ └───────────────────────────┘  │   │',
        '│ └─────────────────────────────────┘   │',
        '└───────────────────────────────────────┘',
        '```',
        '',
        'Therefore:',
        '- A tab\'s `label` becomes the tab name the user sees. Write "Overview" and the user sees "Overview."',
        '- A block\'s `title` becomes the section heading the user sees.',
        '- A field\'s `name` or `label` becomes the visible row content.',
        'Use the page names from the setting below. Do not use placeholder names.',
        '',
        'Four form types (each block uses exactly one):',
        '- **gauge** — a numeric value, optionally with min/max/step and display style.',
        '- **tag** — a status label; add or remove its field to make it appear or disappear.',
        '- **item** — a held or worn thing, optionally with quantity and lore.',
        '- **text** — a free-text paragraph.',
        '',
        'Gauge display mapping:',
        '- If the user asks for "进度条" / "bar", set `display: "bar"`.',
        '- If the user asks for "百分比" / "percent", set `display: "percent"`.',
        '- If the user asks for "点阵" / "dots", set `display: "dots"`.',
        '- If the user asks for "普通数字" / "数字" / "num", set `display: "num"`.',
        '- If the user does not specify a gauge display style, choose the closest style from the meaning: capped resources usually use bar, natural percentages use percent, small-count resources use dots, unbounded counts use num.',
        '',
        'Tool usage:',
        '- StatusRead reads the full status panel.',
        '- When no panel exists, use StatusInit to build the full skeleton strictly following the setting below. If the current panel\'s subjects/tabs/blocks/forms no longer match the current setting because the user changed the status preset, use StatusInit again to rebuild the skeleton. Preserve still-applicable existing field values when rebuilding, and add nothing the current setting does not mention.',
        '- Ongoing maintenance uses StatusPatch only: set or delta a value, push a new field, or remove a field — all within an existing block.',
        '- Never use StatusPatch to add a new tab, add a new block, or change a block\'s form. Structural changes require StatusInit from the current preset. A newly encountered NPC, status condition, or inventory item normally means pushing a field into an existing relationship/status/item block — not inventing a new tab or block.',
        '- Gauge min/max bound the final value. A positive step caps the size of one delta, not the numeric increment grid. Read clamping warnings and the resulting values.',
        '- Delta display is derived by the renderer from before/after values. Do not store delta, lastDelta, or _new in the document.',
        '- Icons are optional. Use only Material Symbols official names in lowercase underscores (e.g. key, medication, checkroom). Omit when unsure.',
        '- If nothing visible on the panel changed this turn, skip StatusPatch entirely.',
        '',
        'The tagged section below contains the user\'s status panel requirements: which blocks to maintain, how to divide them into tabs, and what each tab is called. Build the skeleton strictly from this; do not add anything the tag does not contain.',
        '',
        '<状态栏设定>',
        statusPrompt,
        '</状态栏设定>',
    ].join('\n');
}

export function buildDefaultStatusPanelPrompt(): string {
    return joinLines([
        '状态栏设定',
        '',
        '数值可标范围，0-100。标签动态增删。物品可带数量和来历。',
        '',
        '—— 第一页【概览】——',
        '',
        '角色基础（文本）',
        '  姓名、身份、当前地点',
        '',
        '当前状态（标签）',
        '  临时状态，如：受伤、疲惫、恐惧、中毒、饥饿、隐匿等',
        '',
        '着装（物品，按部位，物品名非角色身体状态和服装状态，而是服装款式）',
        '  头部、上身、下身、足部、配饰',
        '',
        '—— 第二页【能力】——',
        '',
        '身体（数值，0-100）',
        '  力量、体质、敏捷、巧手',
        '',
        '感知（数值，0-100）',
        '  察觉、聆听、搜索、直觉',
        '',
        '心智（数值，0-100）',
        '  意志、学识、话术、威慑',
        '',
        '关系（数值，名称=NPC名，值=好感度 0-100）',
        '  重要NPC对"我"的好感度，每个NPC一条',
        '  新NPC出现时加在这里',
        '',
        '—— 第三页【行囊】——',
        '',
        '背包（物品，可带数量和来历）',
        '  持有的物品、线索、钥匙、消耗品等',
    ]);
}

function joinLines(lines: string[] = []): string { return lines.join('\n').trim(); }
export const statusManagerDomain: ManagerDomainFactory = (preset, options) => ({
    title: 'Status Panel',
    injected: options.workMode === 'manual-chat' ? [] : ['Status panel full document.'],
    reads: options.workMode === 'manual-chat' ? ['StatusRead for the full status panel.'] : [],
    tools: ['StatusRead — read the panel.', 'StatusInit — initialize or rebuild its skeleton from the current setting.', 'StatusPatch — change fields inside existing blocks.'],
    focus: 'Maintain the current visible UI, not a history log. Preset structure and still-applicable existing values remain authoritative.',
    prompt: buildStatusSection(preset.statusPrompt?.trim() || buildDefaultStatusPanelPrompt()),
});
