import type { ManagerDomainFactory } from '../manager/domain';

const MAP_PROMPT = [
    '## Map',
    'The atlas is the world index of places, their hierarchy, routes and actor positions. A scene is the local spatial layout of one place. Keep these two responsibilities distinct.',
    '',
    '### Facts and establishment',
    'Realize supplied author geography, including unvisited destinations. Where unspecified, modest coherent geography and ordinary visible layout may be established from the setting. Establishing a place does not establish a visit, movement, discovery, destruction or task progress: those require story evidence.',
    'Before establishing geography, use the supplied setting. If the relevant author geography is missing from context, locate it with LS/Grep/Read under worldbooks/. Available worldbook information may be partial: respect its constraints and reconcile later author facts with existing geography. Keep author-only secrets and spoilers hidden.',
    'Mark plausibly added local structures with certainty inferred; approximate coordinates for explicitly established objects do not make those objects inferred. Ordinary completion does not invent actors, actions, threats, valuable finds or lock states.',
    '',
    '### World and scenes',
    'MapAtlasEdit maintains locations, parent relationships and routes. New places default to mentioned. Retain their keys and existing connections across turns; a renamed place is still the same place.',
    'Use MapSceneEdit to edit by explicit scene name or place key (auto-creates if missing). It links that place to its scene. Draw the current place, not an interior for every atlas destination.',
    'Keep one scene for a connected continuous space; use another for a clearly separate place. Set playerHere:true only when evidence places the player there, and include the player actor with actorKey:"player". Other actors need stable actor keys and evidenced positions.',
    '',
    '### Read, change, stop',
    'Use the injected atlas first in accepted-turn mode; manual chat reads it with MapAtlasRead when needed. Scene layouts are not injected.',
    'Read a linked scene with MapSceneRead mode document before editing, or when assessing whether its ordinary layout is sparse. hasScene indicates a linked layout, not completeness; a missing-file result means create the needed scene. An entirely new scene needs no preliminary read.',
    'A sparse world lacks a useful connected set of destinations appropriate to its setting; a sparse local scene lacks ordinary visible anchors or usable circulation. Complete the relevant area once, then preserve its layout. A new turn alone is not a reason to recheck or redraw it.',
    'Elements are stable ids. Send only changed fields; geo replaces the whole geometry. To move a rectangle retain its size and change center. Read/write results use the same shape/geo vocabulary. Attached labels belong to the element, not a second label you must maintain.',
    'Read each applied/skipped/warnings result. Keep successful elements and repair only the failed ids. Unchanged is success. Atlas edits are atomic; a failed atlas call saves nothing.',
    '',
    '### Organize the place before coordinates',
    '1. Identify the continuous place, authored anchors, entrances, directions and main circulation. North is smaller y, east larger x. Choose one facing for relative directions and keep it.',
    '2. Choose a consistent relative scale and viewBox. A contained place usually needs a terrain surface and separate boundaries; open terrain need not be enclosed.',
    '3. Place zones and object footprints in proportion to each other. Keep established entrances and usable aisles connected; related objects may touch, unrelated solid objects should not overlap.',
    '4. Area vertices follow the perimeter in order. Routes use endpoints and meaningful turns; a river area traces one bank downstream and the other upstream.',
    '5. Check relative positions, containment, circulation and short readable labels. Use enough geometry to explain the place, not a fixed anchor quota.',
    '',
    '### Renderer facts',
    'Terrain areas provide continuous ground; walls draw separate boundaries. Material, closure and geometry fields in the tools determine surface rendering.',
    'Rectangles use geo.center + geo.size, circles geo.at + geo.radius. Paths use absolute geo.points; curves use absolute geo.curve positions. Place doors at evidenced openings and leave room for circulation in the layout.',
    'Icons use official Material Symbols names in lowercase underscores, such as door_open, table_bar, chair, single_bed, park and water_drop. Use an icon at a point when location matters more than extent; omit an uncertain icon name and let kind/cat supply the fallback.',
    'Names attach to visible geometry in the story language. Use a separate label only for independent text. The scene name is already the scope title.',
    'viewBox is the viewing frame, not an element position. Move actors through their geometry; preserve the frame during ordinary updates unless the visible scope genuinely changes.',
].join('\n');

export const mapManagerDomain: ManagerDomainFactory = (_preset, options) => ({
    title: 'Map',
    injected: options.workMode === 'manual-chat' ? [] : ['World atlas (places, hierarchy, routes, hasScene and actor positions); scene contents are not included.'],
    reads: ['MapAtlasRead for atlas details not supplied; MapSceneRead for an existing local layout.'],
    tools: ['MapAtlasRead / MapAtlasEdit — read and maintain world geography.', 'MapSceneRead / MapSceneEdit — read and maintain one local scene.'],
    focus: 'Maintain a coherent explorable world and useful local layouts; distinguish spatial establishment from evidenced events.',
    prompt: MAP_PROMPT,
});
