import { MEMORY_DATA_COPY } from '../data/memory-copy.js';

export const MEMORY_COPY = Object.freeze({
    tab: 'Agent', toggle: '允许 Agent 维护记忆', scope: '所有聊天',
    behavior: '保存后，从下一次总结开始自动检查与修正记忆。',
    apiHeading: 'Agent API',
    api: '使用共享 Agent API，可在Agent模块任意功能中设置，如小白 OS 的「Agent API」；已配置则无需重复设置。',
    heading: '维护记录', currentChat: '当前聊天', cancel: '停止（已完成部分保留）', repair: '重试更新', more: '更早记录',
    empty: '还没有维护记录', emptyEnabled: '下一次总结后，维护成果会出现在这里。',
    emptyDisabled: '自动维护未开启。', loading: '正在读取…',
    settingsSave: '保存设置', settingsClose: '关闭',
    settingsSaved: '设置已保存', settingsFailed: '设置未能保存',
    before: '修改前', after: '修改后', evidence: '查看原文', absent: '已移除', notSet: '未记录',
    retired: { source_changed: '原文后来有过修改，这条锚点的维护结果已不再使用。',
        anchors_cleared: '锚点后来已被清空，这条记录仅供回看。' },
    summary: '大总结', anchors: '锚点', merges: '事件合并', missing: '锚点未就绪', noChanges: '本次没有修改', coverage: '审阅范围', related: '相关记忆',
    progress: ({ action, saved }) => [MEMORY_COPY.actions[action], saved ? `已保存 ${saved} 项修改` : ''].filter(Boolean).join(' · '),
    actions: { thinking: '正在梳理记忆', reading: '正在查阅', editing: '正在保存成果', compacting: '整理工作上下文' },
    completedRanges: '已完成', pendingRanges: '待维护', noRanges: '无',
    ranges: ranges => ranges.map(range => MEMORY_COPY.sourceRange(range.from, range.to)).join('、') || MEMORY_COPY.noRanges,
    boundary: floor => `截至第 ${floor} 楼`, floor: floor => `第 ${floor} 楼`,
    count: (label, count) => `${label} ${count}`,
    moreChanges: count => `另有 ${count} 项修改`,
    operation: { edit: '修正', delete: '移除', merge: '合并' },
    operationTitle: (action, category, title) => `${action}${category} · ${title}`,
    changesHeading: '修正明细', allChanges: '全部',
    previousPage: '上一页', nextPage: '下一页', latestPage: '最新',
    pagePosition: (page, pages) => `${page} / ${pages}`,
    floorLookup: '锚点楼层', locateFloor: '定位', floorNotFound: '本轮没有这一楼的锚点修改。',
    report: 'AI 汇报', expandReport: '展开全文', collapseReport: '收起全文',
    fields: { title: '事件', timeLabel: '时间', summary: '经过', participants: '人物', causedBy: '前因', memoryRole: '类型',
        s: '人物', p: '事项', o: '内容', since: '起始楼层', retracted: '记录状态', trend: '关系', _isState: '重点保留',
        name: '名称', trajectory: '变化', progress: '进展', moments: '重要时刻', text: '内容', weight: '重要程度',
        from: '称呼', to: '对应人物', evidence: '依据', semantic: '当时发生的事', where: '地点', edges: '人物与行动' },
    yes: '是', no: '否', retained: '保留', retracted: '已撤回',
    sourceRange: (start, end) => start === end ? `第 ${start} 楼` : `第 ${start}–${end} 楼`,
    relation: edge => `${edge.s} · ${edge.r} · ${edge.t}`,
    source: { heading: '原文', close: '返回成果', previous: '上一楼', next: '下一楼', more: '继续阅读', retry: '重试',
        note: '显示当前聊天原文；若后来编辑过，内容可能与维护时不同。',
        loading: '正在读取原文…', unavailable: '这段原文已无法查看，可能已删除或对应维护记录已撤销。',
        roles: { user: '用户', assistant: '角色', system: '系统' } },
    collections: { events: '事件', facts: '持续事实', characters: '人物', arcs: '弧光', keywords: '关键词', characterAliases: '别名', anchors: '逐楼锚点' },
    anchorStates: { missing: '未生成', fail: '提取失败' },
    states: { idle: '', queued: '等待前一轮结束', running: '正在检查记忆…', saving: '正在保存修改…', indexing: '修改已保存，正在更新记忆检索…',
        completed: '维护已结束', partial: '部分完成，剩余范围将在下次总结后继续。', interrupted: '本次维护未收尾，已保存的修改保留。',
        turn_limit: '本次维护已达到调用上限，已保存的修改保留。', input_limit: '本次维护已达到上下文上限，已保存的修改保留。',
        cancelled: '维护已停止，已保存的修改保留。', failed: '本次维护未完成，已保存的修改保留。', unconfirmed: MEMORY_DATA_COPY.unconfirmed,
        source_invalid: MEMORY_DATA_COPY.sourceInvalid, history_invalid: MEMORY_DATA_COPY.historyInvalid },
    indexPending: '修改已保存，部分内容还不能用于记忆检索。重试只更新检索，不会重新维护。',
    errors: { not_configured: '请先在 Agent API 中设置模型和服务地址。', no_boundary: '当前聊天还没有可维护的总结。',
        agent_auth: '共享 Agent API 的凭据不可用，请在 Agent API 设置中更新。',
        agent_balance: '共享 Agent API 余额不足。', agent_rate: '共享 Agent API 暂时限流。',
        agent_model: '共享 Agent API 当前不提供所选模型。',
        conflict: '原文或记忆发生了变化，维护已停止；此前保存的部分保留。',
        compaction_failed: '工作上下文整理失败，已完成的范围和修改保留。',
        agent_failed: '服务暂时不可用，已保存的修改保留。', empty_response: '模型没有返回内容，已保存的修改保留。',
        metadata_not_saved: '服务器未保存修改，已恢复修改前的记忆。', metadata_save_conflict: '服务器内容已变化，保存结果需核对。',
        metadata_save_unconfirmed: '暂时无法确认修改是否保存，请重新加载当前聊天后核对。', metadata_target_unavailable: '找不到当前聊天文件。',
        index_failed: '记忆检索未能更新。', index_read_failed: '暂时无法检查记忆检索是否可用。', load_failed: '维护记录暂时无法读取。' },
});
