import type { ManagerDomainFactory } from '../manager/domain';
function buildMemorySection(statePrompt: string, characterPrompt: string): string {
    return [
        '---',
        '',
        '## Memory',
        '',
        'You maintain this session\'s long-term memory as Markdown under `memory/`.',
        '',
        'Two file types, fixed paths:',
        '- Global facts → `memory/state.md` (a single file, not a directory).',
        '- Character files → `memory/characters/<name>.md` (one file per character, filename = character name).',
        '- A character filename and the character name written inside that file must exactly match the spelling used in the RP text. Never translate, transliterate, convert between Simplified and Traditional Chinese, or substitute an English name; retrieval depends on exact name matching.',
        '- Routing: global facts and the player\'s durable state go to `state.md`; other characters\' durable changes go to their own files. Move misplaced NPC material into the matching character file.',
        '',
        'What not to do:',
        '- Do not create other memory paths (no `session.md`, no `turns/*.md`, no custom paths).',
        '- Keep the player/user/message author\'s durable state in `state.md`, even when they have a named RP character. Character files are for other established named characters.',
        '- Do not copy status panel content into memory. Do not use memory files as the status panel\'s data source.',
        '',
        'Tool usage:',
        '- LS to see `memory/` directory structure. Grep to search content. Read to read files.',
        '- Edit to change specific lines of an existing file (insert/replace/delete). Write to write an entire file.',
        '- Edit/Write may only target `memory/state.md` and `memory/characters/<name>.md`.',
        '- Grep with `path:"memory/"` to check whether a fact is already stored. Grep with `path:"chat/"` to check whether something actually happened in the RP.',
        '- Read may return only part of a large file; use `nextOffset` to continue or `tail` to read the end.',
        '',
        'When to write:',
        '- Accepted-turn: write only when the accepted reply actually establishes a new long-term fact, current state, character change, or something that must carry forward to the next turn. If nothing material changed, skip.',
        '- Record only established facts. Keep what happened, what the user requested, what you inferred, and what is still unconfirmed clearly separate. Do not write guesses, plans, hidden reasoning, or unconfirmed psychology as settled facts. Character psychology and secrets become facts only after the RP source clearly establishes them.',
        '- The sole controlled exception is the absolute-date continuity rule in the user settings below: an inferred date must stay visibly marked `[推定]`, be used only as a backstage timeline anchor, and be corrected when later RP establishes an explicit date.',
        '- Memory files are maintained documents, not append-only turn logs. Keep their structure coherent, deduplicated, current, and easy to retrieve.',
        '- Memory is for a future model to retrieve and read. Keep headings useful and content clear and editable.',
        '',
        'The two tagged sections below are the user\'s settings for how these two file types should be internally formatted, what content scope to cover, and what selection rules to follow. File paths and responsibilities are fixed by the system; the tags only govern internal format. Do not extend beyond what the tags contain.',
        '',
        '<全局记忆设定>',
        statePrompt,
        '</全局记忆设定>',
        '',
        '<人物记忆设定>',
        characterPrompt,
        '</人物记忆设定>',
    ].join('\n');
}

export function buildDefaultStateMemoryPrompt(): string {
    return joinLines([
        '目标：维护影响后续剧情的事件与世界状态，供后续每一轮召回，不穿帮、不矛盾。',
        '判断标准只有一条：忘了它，后续会出错或冲突吗？不会就不写。',
        '',
        '写入准入：',
        '- 只写：相遇、冲突、揭示、抉择、羁绊、转变、收束，或会改变后续的关键日常。',
        '- 不写：普通对白、气氛、一次性动作、重复情绪、无后果寒暄、状态栏、系统文字。',
        '',
        '时间规则（最重要）：',
        '- 每条事件必须有绝对日期，禁止"昨天/最近/之后/第一天"。',
        '- 无明确时间时，按世界观推定一个绝对日期，来源标 [推定]，并在后续持续沿用，保证时间轴内部稳定。',
        '- 剧情后来出现能确定该事件日期的明确时间锚点时，回查并修改相关 [推定] 日期，不保留冲突的旧推定。',
        '- [推定] 只是后台连续性锚点，不得表述成剧情已经明确确认的日期。',
        '',
        '格式（严格对齐，每条正文 ≤ 50 字）：',
        '## 事件时间线',
        '- [YYYY-MM-DD HH:mm｜剧情] 地点｜标题：谁对谁做了什么 → 结果 → 后果',
        '- [YYYY-MM-DD｜推定] 地点｜标题：谁对谁做了什么 → 结果 → 后果',
        '',
        '## 世界状态',
        '说明：当前持续成立的世界事实（局势/规则/地理/时代/历法/货币），以及影响后续的玩家持续状态。',
        '- 主体｜谓词｜当前值（来源）',
        '',
        '写法约束：',
        '- 一条只记一件事；超 50 字说明你想记两件，拆开或只留结果与后果。',
        '- 每轮先维护现有内容：同一事件合并，旧结论改写，冲突值删除；只有真正新发生、且会影响后续的事件才新增条目。',
        '- 世界状态只保留当前有效值；状态发生变化时替换旧值，不保留一串历史版本。',
        '- 修改前先读现有记忆；不确定查 chat/，不靠印象补设定。',
        '- NPC 的状态/伤势/持有物归人物记忆；玩家的重要持续状态记在本文件，不为玩家另建人物档案。',
    ]);
}

export function buildDefaultCharacterMemoryPrompt(): string {
    return joinLines([
        '目标：维护 NPC 的处境、关系、持续状态与未了之事，供后续召回不演崩。',
        '只为有世界内名字、且非当前玩家的角色建档（当前用户/玩家名见 Runtime Context；若未知，先查证，不要猜）。',
        '',
        '写入准入：',
        '- 只在实质变化时写：关系转向、身份揭示、目标改变、秘密暴露、承诺/债务成立、伤势/限制持续。',
        '- 不写：单纯出场、一句普通话、一次性动作、短暂情绪、猜测、隐藏推理、状态栏文字。',
        '',
        '时间规则：',
        '- 关键节点必须带绝对日期：无明确时间时推定并标 [推定]，后续持续沿用；剧情出现明确时间锚点后，回查并修改相关推定日期。',
        '- [推定] 只是后台连续性锚点，不得表述成剧情已经明确确认的日期。',
        '',
        '格式（严格对齐，每条正文 ≤ 50 字）：',
        '## 当前状态',
        '- 一句话：现在的处境与想要什么',
        '',
        '## 弧光',
        '- 阶段：<=15字概括',
        '- 节点：[YYYY-MM-DD｜来源] 地点｜发生了什么 → 改变了什么',
        '',
        '## 关系趋势',
        '- 对X：当前关系｜最近一次改变它的事件(日期)｜当前后果',
        '',
        '## 硬事实',
        '- 主体｜谓词｜当前值（来源）   ← 身份/位置/伤势/持有物/持续限制',
        '',
        '## 秘密与未了之事',
        '- 类型｜内容｜对谁｜风险/后果   ← 秘密/承诺/债务/把柄/悬置威胁',
        '',
        '去重与维护：',
        '- 同一信息只写一处：影响关系写关系趋势，纯背景写硬事实，发生过的写弧光节点。',
        '- 当前状态直接维护成“现在是什么”，覆盖已经失效的旧处境，不追加历次状态。',
        '- 同一对象的关系趋势只保留一条当前记录；关系变化时改写原条目，并保留最近一次关键变化。',
        '- 描述同一次转变的弧光节点应合并；硬事实发生变化时替换旧值，不并列保存互相冲突的版本。',
        '- 已了结的承诺/债务、已收束的关系，压成一句结论或删除，不留过程。',
        '- 优先改旧条目；修改前先读目标人物记忆，不确定查 chat/。',
        '- 不为用户建档。',
    ]);
}

function joinLines(lines: string[] = []): string { return lines.join('\n').trim(); }
export const memoryManagerDomain: ManagerDomainFactory = (preset, options) => ({
    title: 'Memory',
    injected: ['Global memory `state.md` in full.', ...(options.workMode === 'manual-chat' ? [] : ['Character memory filename list only (not file contents).'])],
    reads: ['Read `memory/characters/<name>.md` for a specific character\'s full file.'],
    tools: ['Edit — edit selected lines in an existing memory file.', 'Write — replace a complete memory file.'],
    focus: 'Keep durable facts accurate, consolidated and retrievable. Update, merge, move, compress, remove or skip before adding a genuinely new entry; a new turn is not itself a reason to append.',
    prompt: buildMemorySection(preset.statePrompt?.trim() || buildDefaultStateMemoryPrompt(), preset.characterPrompt?.trim() || buildDefaultCharacterMemoryPrompt()),
});
